---
downloads: ~/.ansible-downloads/

the_user: "{{ ansible_user_id }}"

configure_dotfiles: true
dotfiles_repo: https://github.com/sleeper/dotfiles.git
dotfiles_repo_accept_hostkey: true
dotfiles_repo_local_destination: ~/dotfiles
dotfiles_repo_version: main

homebrew_installed_packages: []
homebrew_taps: []

homebrew_cask_appdir: /Applications
homebrew_cask_apps: []

mas_installed_apps: []
mas_email: ""
mas_password: ""

npm_packages: []
pip_packages: []

configure_powerline: true
powerline_dest_dir: "~/config/powerline"

configure_pl10k: true
p10k_path: "~/.oh-my-zsh/custom/themes/powerlevel10k"


# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []
