---
- hosts: all

  vars_files: 
    - default_config.yml
  pre_tasks:
    - name: Include playbook configuration.
      include_vars: "{{ item }}"
      with_fileglob:
        - "{{ playbook_dir }}/config.yml"
      tags: ['always']

  roles:
    - role: geerlingguy.mac.homebrew
      tags: ['homebrew']
    - role: geerlingguy.mac.mas
      when: mas_installed_apps or mas_installed_app_ids
      tags: ['mas']

  tasks:
    - import_tasks: tasks/dotfiles.yml
      when: configure_dotfiles
      tags: ['dotfiles']

    - import_tasks: tasks/iterm2.yml
      when: configure_iterm2
      tags: ['iterm2']

    - import_tasks: tasks/omz.yml
      when: configure_omz
      tags: ['omz']

    - import_tasks: tasks/powerlinefonts.yml
      when: configure_powerline
      tags: ['powerline']

    - import_tasks: tasks/powerlevel10k.yml
      when: configure_pl10k
      tags: ['pl10k']

    - import_tasks: tasks/extra-packages.yml
      tags: ['extra-packages']

    - name: Run configured post-provision ansible task files.
      include_tasks: "{{ outer_item }}"
      loop_control:
        loop_var: outer_item
      with_fileglob: "{{ post_provision_tasks|default(omit) }}"
      tags: ['post']

