---

- name: download powerline-fonts repository from github
  git:
    repo: 'https://github.com/powerline/fonts.git'
    dest: "{{ powerline_dest_dir }}"
  tags:
    - powerline-fonts
- name: install powerline fonts.
  command: "{{ powerline_dest_dir}}/install.sh"
  failed_when: false

